services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    volumes:
      - .:/src
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    networks:
      - app-network

  # Mailpit service for email testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge